name: Test

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
      
      - name: Setup Python 3.10
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run tests (Pytest)
        run: pytest -vv
